### ISSUE TITLE
Unable to stream gcode with imported profile

### ISSUE THREAD

**Issue by SynWillinger** [SynDaverCO/symple-slicer#91] opened 2020-07-09 19:34 UTC
**Describe the bug**
After importing a custom profile, attempting to stream gcode gives the error "Error: No serial port information for this profile"

**Details**
 - SympleSlicer Version: Desktop build from 7-9

**To Reproduce**
1. Go to "Advanced Features" and upload profile under "Import Settings"
2. Load model and slice
3. Select "Send to connected printer" option under "Print Options" on the "Print and Preview" page

**Expected behavior**
SympleSlicer should be able to find the machine and print

**Screenshots**
![symple_serial_error](https://user-images.githubusercontent.com/60902184/87082726-b024da00-c1e8-11ea-8ff1-8438fb518dd2.PNG)

**Additional context**
Here is the profile I was trying to load: 
[profile.toml.txt](https://github.com/SynDaverCO/symple-slicer/files/4899127/profile.toml.txt)

**Comment by marciot** [comment] 2020-07-10 16:02
This is because I added information to the profiles for the serial port. That same information needs to be added to any exported profiles for printing to work. Will close this as won't fix, as the cause is an obsolete profile.

```
[usb]

flasher                                        = "bossa"
firmware                                       = "../machine_firmware/SynDaver_Axi_Marlin_R2.bin"
baudrate                                       = 250000
samba_vendor_id                                = "03EB"
samba_product_id                               = "6124"
marlin_vendor_id                               = "27B1"
marlin_product_id                              = "0001"
stop_print_gcode                               = """
M140 S0                                        ; turn off heated bed
M104 S0 T0                                     ; turn off heater T0
M107                                           ; turn off fan
M84 X Y                                        ; disable X and Y steppers (not Z)
M77                                            ; stop print timer
G91                                            ; relative positioning
G0 Z15 F600                                    ; raise nozzle
G90                                            ; absolute positioning
G0 X170 Y290 F3000                             ; park nozzle
M117 Print stopped.
"""
```

**Closed by marciot** 2020-07-10 16:02 UTC
Labels: Desktop
