### ISSUE TITLE
Import Setting being ignored

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#101] opened 2020-08-03 22:13 UTC
**Describe the bug**
When I import a profile for testing, my Infill pattern does not apply to Symple Slicer and is not changed with my import. 

**Details**
 - SympleSlicer Version: beta 1.0.8
 - Browser [e.g. chrome, safari]: Chrome

**To Reproduce**
Import a profile with settings "infill_pattern = "cubicsubdiv"" and see that the slice settings still read "lines" and the print produces infill as Lines. 

**Expected behavior**
Infill Pattern to be overridden and read the appropriate pattern when imported. 

**Screenshots**

![lines-vs-cubicsubdiv](https://user-images.githubusercontent.com/65256117/89232192-317f4a80-d5a4-11ea-879f-86efc147b5d7.JPG)

**Comment by marciot** [comment] 2020-08-04 14:02
Can you upload the profile you are trying to import?

**Comment by synsuiter** [comment] 2020-08-04 14:38
I cant upload the .toml but I converted it to .txt here:

[ABS-0.5noz_PRODUCTION-PROFILE_BASE-003.txt](https://github.com/SynDaverCO/symple-slicer/files/5022720/ABS-0.5noz_PRODUCTION-PROFILE_BASE-003.txt)

**Comment by marciot** [comment] 2020-08-05 14:15
I am able to confirm it. Fixing this will require investigation and significant work. It will need to wait until the 1.0.9 release after all the desktop stuff is rolled in.

**Comment by marciot** [comment] 2020-08-05 14:24
The reason this is happening is an interaction between "infill_sparse_density" and "infill_pattern". The formula for "infill_pattern" is:

'lines' if infill_sparse_density > 25 else 'grid'

So if you set both "infill_sparse_density" and "infill_pattern" in your profile, then "infill_pattern" will be forced to be "lines", in accordance to the formula.

I'm not sure what the correct behavior is for when the profile specifies things that contradict the formulas

**Comment by marciot** [comment] 2020-08-05 14:28
BTW, here is a trick for you. If you click the three dots in Chrome, then select "More Tools" and "Developer Tools". Then type the following incarnation in the Console:

```slicer.config.verbose=true;```

Then you when you load a profile it will print all the settings and how they were computed:

![image](https://user-images.githubusercontent.com/6752228/89424903-91d1d180-d6f5-11ea-9c5c-d192f5756af5.png)

This may help in understand what is happening in the future.

**Comment by marciot** [comment] 2020-08-05 14:39
I've confirmed this bug has already been fixed in the latest code. The reason the fix isn't in the beta is because we backtracked to 1.0.7, which lacks some of the improvements in the 1.0.8 code we abandoned (and which will now be present in 1.0.9)

**Comment by marciot** [comment] 2020-08-05 14:59
Nevermind previous comment. There was another bug. Let me see what I can do.

**Comment by marciot** [comment] 2020-08-05 15:14
Okay, I pushed a fix to this to the beta.

**Comment by marciot** [comment] 2020-08-07 14:08
@synsuiter: Can this ticket be closed?

**Closed** 2020-08-07 17:20 UTC
